export const breakfastItems = [
    { name: "Chilaquiles verdes", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "90.00", pricePackage: "120.00" },
    { name: "Chilaquiles verdes con huevo", quantity: "100 grs + 120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "110.00", pricePackage: "140.00" },
    { name: "Chilaquiles verdes con pollo", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "120.00", pricePackage: "150.00" },
    { name: "Chilaquiles verdes con aguja norteña", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "150.00", pricePackage: "180.00" },
    { name: "Chilaquiles verdes con arrachera marinada", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles verdes con rib eye", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles verdes con new york", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles verdes con sirloin", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "90.00", pricePackage: "120.00" },
    { name: "Chilaquiles rojos con huevo", quantity: "100 grs + 120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "110.00", pricePackage: "140.00" },
    { name: "Chilaquiles rojos con pollo", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "120.00", pricePackage: "150.00" },
    { name: "Chilaquiles rojos con aguja norteña", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "150.00", pricePackage: "180.00" },
    { name: "Chilaquiles rojos con arrachera marinada", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos con rib eye", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos con new york", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos con sirloin", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Enchiladas verdes con pollo", quantity: "160 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "116.00", pricePackage: "146.00" },
    { name: "Enchiladas verdes con huevo", quantity: "120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "126.00", pricePackage: "156.00" },
    { name: "Enchiladas verdes con aguja norteña", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "152.00", pricePackage: "182.00" },
    { name: "Enchiladas verdes con arrachera marinada", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas verdes con rib eye", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas verdes con new york", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas verdes con sirloin", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con pollo", quantity: "160 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "116.00", pricePackage: "146.00" },
    { name: "Enchiladas rojas con huevo", quantity: "120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "126.00", pricePackage: "156.00" },
    { name: "Enchiladas rojas con aguja norteña", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "152.00", pricePackage: "182.00" },
    { name: "Enchiladas rojas con arrachera marinada", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con rib eye", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con new york", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con sirloin", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas suizas con pollo", quantity: "160 grs", accompaniment: "cebolla, cilantro, crema, queso panela, queso", priceNormal: "135.00", pricePackage: "165.00" },
    { name: "Enchiladas veracruzanas", quantity: "180 grs", accompaniment: "chorizo, cilantro, crema, queso panela, aguacate", priceNormal: "115.00", pricePackage: "145.00" },
    { name: "Huevos divorciados", quantity: "120 grs", accompaniment: "frijol, crema, queso panela, cilantro", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Huevos a la mexicana", quantity: "120 grs", accompaniment: "frijol, ensalada, tortillas", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Huevos rancheros", quantity: "120 grs", accompaniment: "jamon, frijoles, tortillas", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Huevos revueltos", quantity: "120 grs", accompaniment: "frijol, ensalada, tortillas. con jamon 70grs, tocino 90grs, o chorizo 90grs", priceNormal: "89.00", pricePackage: "119.00" },
  ];
  
  export const entranceItems = [
    { name: "Queso fundido", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "125.00" },
    { name: "Queso fundido con arrachera", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "165.00" },
    { name: "Queso fundido con aguja norteña", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "165.00" },
    { name: "Queso fundido con rib eye", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "185.00" },
    { name: "Queso fundido con new york", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "185.00" },
    { name: "Queso fundido con sirloin", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "185.00" },
    { name: "Guacamole", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "145.00" },
    { name: "Pescadilla", quantity: "3 pz 500 grs", accompaniment: "aguacate, limon", price: "83.00" },
    { name: "Sopes", quantity: "", accompaniment: "", price: "" },
    { name: "Huaraches", quantity: "", accompaniment: "", price: "" },
  ];

  export const coldEntranceItems = [
    { name: "Cóctel de camaron chico", quantity: "80 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "95.00" },
    { name: "Cóctel de camaron grande", quantity: "140 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "145.00" },
    { name: "Cóctel de campechano chico", quantity: "80 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "95.00" },
    { name: "Cóctel de campachano grande", quantity: "140 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "145.00" },
    { name: "Tostada de atun", quantity: "1 pz 80 grs", accompaniment: "cebolla, jitomate, aguacate", price: "95.00" },
    { name: "Tostada de pescado", quantity: "1 pz 60 grs", accompaniment: "cebolla, jitomate, aguacate", price: "95.00" },
    { name: "Tostada de pulpo", quantity: "1 pz 60 grs", accompaniment: "cebolla, jitomate, aguacate", price: "125.00" },
    { name: "Tostada de camaron", quantity: "1 pz 60 grs", accompaniment: "cebolla, jitomate, aguacate", price: "125.00" },
    { name: "Aguachile rojo", quantity: "", accompaniment: "", price: "" },
    { name: "Aguachile negro", quantity: "", accompaniment: "", price: "" },
    { name: "Aguachile verde", quantity: "", accompaniment: "", price: "" },
  ];
  
  export const foodItems = [
    { name: "Camarones momia", quantity: "150 grs", accompaniment: "ensalada de la casa", price: "225.00" },
    { name: "Atun a la parrilla", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "213.00" },
    { name: "Salmon a la parrilla", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "245.00" },
    { name: "Ensalada de frutos rojos", quantity: "180 grs", accompaniment: "aderezo de la casa, queso cabra", price: "165.00" },
    { name: "Ensalada de melon", quantity: "200 grs", accompaniment: "queso panela", price: "115.00" },
    { name: "Arrachera", quantity: "200 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "295.00" },
    { name: "Aguja norteña", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "295.00" },
    { name: "Rib eye", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "345.00" },
    { name: "New york", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "345.00" },
    { name: "Sirloin", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "345.00" },
    { name: "Pechuga al limon", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "165.00" },
    { name: "Pechuga al chipotle", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "185.00" },
    { name: "Tacos de arrachera", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "58.00" },
    { name: "Tacos de aguja norteña", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "58.00" },
    { name: "Tacos de rib eye", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "68.00" },
    { name: "Tacos de new york", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "68.00" },
    { name: "Tacos de sirloin", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "68.00" },
    { name: "Tacos de pechuga al limon", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "49.00" },
    { name: "Tacos de pechuga al chipotle", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "49.00" },
    { name: "Tacos queso carne", quantity: "", accompaniment: "Bisteck, cebolla acitrónada, queso y tortilla de harina.", price: "48.00" },
    { name: "Hamburguesa clasica", quantity: "1 pz 180 grs", accompaniment: "queso americano. lechuga, jitomate, cebolla, tocino, papas a", price: "175.00" },
    { name: "Hamburguesa doble carne", quantity: "1 pz 300 grs", accompaniment: "queso americano. lechuga, jitomate, cebolla, tocino, papas a", price: "195.00" },
    { name: "Hamburguesa tocinito", quantity: "1 pz 180 grs", accompaniment: "queso chihuahua. lechuga, jitomate, cebolla, tocino, papas a la francesa", price: "185.00" },
    { name: "Hamburguesa queso + queso", quantity: "1 pz 180 grs", accompaniment: "queso chihuahua, queso oaxaca. lechuga, jitomate, cebolla, papas", price: "185.00" },
    { name: "Hamburguesa de la granja", quantity: "1 pz 300 grs", accompaniment: "queso chihuahua, lechuga, jitomate, cebolla, huevo, papas a la francesa", price: "185.00" },
    { name: "Hamburguesa mar y tierra", quantity: "1 pz 240 grs", accompaniment: "queso oaxaca, lechuga, jitomate, cebolla, papas a la francesa", price: "195.00" },
    { name: "Hamburguesa la de casa", quantity: "1 pz 150 grs Arrachera", accompaniment: "queso oaxaca, queso chihuahua, lechuga, jitomate, cebolla", price: "228.00" },
    { name: "Hamburguesa de pollo", quantity: "1 pz 180 grs", accompaniment: "queso americano, lechuga, jitomate, cebolla, salsa bufalo, papas", price: "185.00" }
];

export const drinkItems = [
    { name: "Kamikaze", quantity: "37.5 ml", price: "65.00", ingredients: "Smirnoff, Controy, Jugo de Limón Verde" },
    { name: "Lemon drop", quantity: "45 ml", price: "65.00", ingredients: "Smirnoff, Jugo de Limón Amarillo, Jarabe Natural, Gajo de Limón Amarillo con Azúcar" },
    { name: "B52", quantity: "45 ml", price: "65.00", ingredients: "Kahlua, Baileys, Controy" },
    { name: "Black russian", quantity: "67.5 ml", price: "65.00", ingredients: "Smirnoff, Kahlua" },
    { name: "White russian", quantity: "150 ml", price: "65.00", ingredients: "Smirnoff, Kahlua, Leche" },
    { name: "Daiquiri clasico", quantity: "105 ml", price: "65.00", ingredients: "Bacardi blanco, Jugo de limón verde, Jarabe natural" },
    { name: "Orgasm", quantity: "90 ml", price: "65.00", ingredients: "Kahlua, Disaronno, Baileys, Leche" },
    { name: "Caipiroska", quantity: "82.5 ml", price: "65.00", ingredients: "Gajo de limón verde, Jarabe natural, Smirnoff" },
    { name: "Godmother", quantity: "60 ml", price: "65.00", ingredients: "Smirnoff, Disaronno" },
    { name: "Screaming orgasm", quantity: "105 ml", price: "65.00", ingredients: "Smirnoff, Kahlua, Disaronno, Baileys, Leche" },
    { name: "Tinto de verano", quantity: "150 ml", price: "65.00", ingredients: "Sprite, Altozano Ensamble Crianza, Rodaja de Limón Amarillo" },
    { name: "Vodka & tonic", quantity: "180 ml", price: "65.00", ingredients: "Smirnoff, Agua Quina, Rodaja de Limón Verde" },
    { name: "Expresso martini", quantity: "127.5 ml", price: "90.00", ingredients: "Smirnoff, Kahlua, Expresso, Jarabe Natural, Granos de Café" },
    { name: "Cuba libre", quantity: "180 ml", price: "90.00", ingredients: "Bacardi Blanco, Coca-Cola, Gajo de Limón Verde" },
    { name: "Cubata", quantity: "180 ml", price: "90.00", ingredients: "Bacardi Añejo, Coca-Cola, Gajo de Limón Verde" },
    { name: "Fidel castro", quantity: "180 ml", price: "90.00", ingredients: "Jugo de limón verde, Bacardi añejo, Ginger ale, Gajo de limón verde" },
    { name: "Colorado bulldog", quantity: "150 ml", price: "90.00", ingredients: "Smirnoff, Kahlua, Leche, Coca-Cola" },
    { name: "Godfather", quantity: "60 ml", price: "90.00", ingredients: "Jim Beam White, Disaronno" },
    { name: "Cape codder", quantity: "180 ml", price: "90.00", ingredients: "Smirnoff, Jugo de Arándano, Gajo de Limón Verde" },
    { name: "Margarita clásica", quantity: "112.5 ml", price: "90.00", ingredients: "Sal, Jose cuervo tradicional, Controy, Jugo de limón verde, Jarabe natural" },
    { name: "Woo woo", quantity: "180 ml", price: "90.00", ingredients: "Smirnoff, Flamingo de Durazno, Jugo de Arándano" },
    { name: "White lady", quantity: "112.5 ml", price: "90.00", ingredients: "Beefetear, Controy, Jugo de limón amarillo, Jarabe natural, Cascara de limón amarillo" },
    { name: "Boulevardier", quantity: "90 ml", price: "90.00", ingredients: "Jim Beam White, Vermut Dulce, Campari, Rodaja de Naranja" },
    { name: "Pink lady", quantity: "120 ml", price: "90.00", ingredients: "Beefetear, Controy, Jugo de limón amarillo, Jarabe natural, Granadina, Cascara de limón amarillo" },
    { name: "Americano", quantity: "90 ml", price: "90.00", ingredients: "Vermut Dulce, Campari, Agua Mineral, Rodaja de Naranja" },
    { name: "Mojito", quantity: "180 ml", price: "90.00", ingredients: "Gajo de limón verde, Jarabe natural, Hierbabuena, Bacardi blanco, Agua mineral, Punta de hierbabuena" },
    { name: "Wet martini", quantity: "75 ml", price: "90.00", ingredients: "Smirnoff/Beefeter, Vermut seco, Aceituna/Cascara de limón amarillo" },
    { name: "Negroni", quantity: "90 ml", price: "90.00", ingredients: "Beefetear, Vermut Dulce, Campari, Rodaja de Naranja" },
    { name: "Gin & tonic", quantity: "180 ml", price: "110.00", ingredients: "Beefeater, Agua Quina, Rodaja de Limón Verde" },
    { name: "Gin basil smash", quantity: "105 ml", price: "110.00", ingredients: "Gajo de limón verde, Beefetear, Jugo de limón amarillo, Jarabe natural, Albahaca, Hoja de albahaca" },
    { name: "Southside", quantity: "105 ml", price: "110.00", ingredients: "Beefetear, Jugo de limón amarillo, Jarabe natural, Hierbabuena, Punta de hierbabuena" },
    { name: "Mezcaloni", quantity: "90 ml", price: "110.00", ingredients: "Mono Araña, Vermut Dulce, Campari, Cascara de Naranja" },
    { name: "Dry martini", quantity: "60 ml", price: "110.00", ingredients: "Smirnoff/Beefeter, Vermut seco, Aceituna/Cascara de limón amarillo" },
    { name: "Hemingway daiquiri", quantity: "112.5 ml", price: "110.00", ingredients: "Bacardi blanco, Flamingo de cereza, Jugo de limón verde, Jugo de toronja, Cereza" },
    { name: "Dirty martini", quantity: "90 ml", price: "110.00", ingredients: "Smirnoff/Beefeter, Vermut seco, Salmuera, Aceituna/Cascara de limón amarillo" },
    { name: "Cosmopolitan", quantity: "112.5 ml", price: "110.00", ingredients: "Smirnoff, Controy, Jugo de arándano, Jugo de limón verde, Cascara de naranja" },
    { name: "Amf", quantity: "180 ml", price: "110.00", ingredients: "Smirnoff, Beefetear, Mono Araña, Flamingo De Curazao, Jugo De Limon Amarillo, Jarabe Natural, Sprite, Cascara De Limón Amarillo" },
    { name: "Tommy's margarita", quantity: "135 ml", price: "110.00", ingredients: "Sal, Jose cuervo tradicional, Jugo de limón verde, Miel de agave" },
    { name: "Bull", quantity: "150 ml", price: "110.00", ingredients: "Jugo de Limón Verde, Jarabe Natural, Bacardi Blanco, Bohemia Oscura, Gajo de Limón Verde" },
    { name: "Lychburg limonade", quantity: "180 ml", price: "110.00", ingredients: "Jim beam white, Controy, Jugo de limon amarillo, Jarabe natural, Sprite, Gajo de limon amarillo" },
    { name: "Negroni sbagliato", quantity: "90 ml", price: "125.00", ingredients: "Cinzano To Spritz, Vermut Dulce, Campari, Rodaja de Naranja" },
    { name: "Carajillo", quantity: "120 ml", price: "125.00", ingredients: "Licor 43, Expresso, Granos de Café" },
    { name: "Long island iced tea", quantity: "180 ml", price: "125.00", ingredients: "Smirnoff, Beefetear, Bacardi blanco, Jose cuervo tradicional, Controy, Jarabe natural, Jugo de limon amarillo, Coca-cola, Gajo de limon amarillo" },
    { name: "Clover club", quantity: "120 ml", price: "125.00", ingredients: "Beefetear, Jugo de limón amarillo, Néctar de frambuesa, Clara de huevo, Frambuesa" },
    { name: "Mezcalita", quantity: "105 ml", price: "125.00", ingredients: "Tajín, Mono Araña, Jugo de Limón Verde, Jarabe Natural, Punta de Hierbabuena" },
    { name: "John collins", quantity: "180 ml", price: "125.00", ingredients: "Jim beam white, Jugo de limon amarillo, Jarabe natural, Agua mineral, Gajo de limon amarillo" },
    { name: "Mimosa", quantity: "240 ml", price: "125.00", ingredients: "Jugo de Naranja, Cinzano To Spritz" },
    { name: "Back room", quantity: "90 ml", price: "125.00", ingredients: "Beefetear, Vermut Seco, Frangelico, Ferrero Rocher" },
    { name: "Tequila sunrise", quantity: "180 ml", price: "125.00", ingredients: "Jose Cuervo Tradicional, Jugo de Naranja, Granadina" },
    { name: "Bloody mari", quantity: "165 ml", price: "135.00", ingredients: "Smirnoff, Jugo de Tomate, Petroleo, Sal, Pimienta Negra, Jugo de Limón Verde, Punta de Apio" },
    { name: "Tom collins", quantity: "180 ml", price: "135.00", ingredients: "Beefetear, Jugo de limon amarillo, Jarabe natural, Agua mineral, Gajo de limon amarillo" },
    { name: "Beverly hills iced tea", quantity: "180 ml", price: "135.00", ingredients: "Smirnoff, Beefeater, Bacardi Blanco, Jose Cuervo Tradicional, Controy, Jarabe Natural, Jugo de Limón Amarillo, Cinzano To Spritz, Gajo de Limón Amarillo" },
    { name: "Long beach iced tea", quantity: "180 ml", price: "135.00", ingredients: "Smirnoff, Beefeater, Bacardi Blanco, Jose Cuervo Tradicional, Controy, Jarabe Natural, Jugo de Limón Amarillo, Jugo de Arándano, Gajo de Limón Amarillo" },
    { name: "Piña colada", quantity: "180 ml", price: "135.00", ingredients: "Jugo de Piña, Bacardi Blanco, Flamingo de Coco, Jugo de Limón Verde, Néctar de Coco, Rodaja de Piña, Cereza" },
    { name: "Sex on the beach", quantity: "180 ml", price: "135.00", ingredients: "Smirnoff, Flamingo de durazno, Jugo de naranja, Jugo de arándano" },
    { name: "Pitufo", quantity: "180 ml", price: "135.00", ingredients: "Malibu, Flamingo de Curazao, Jugo de Piña, Sprite, Rodaja de Piña, Cereza" },
    { name: "Red snapper", quantity: "165 ml", price: "155.00", ingredients: "Beefetear, Jugo de Tomate, Petroleo, Sal, Pimienta Negra, Jugo de Limón Verde, Punta de Apio" },
    { name: "Last word", quantity: "90 ml", price: "155.00", ingredients: "Beefetear, Flamingo de cereza, Chartreuse verde, Jugo de limón verde, Cereza" },
    { name: "Frangelico spritz", quantity: "127.5 ml", price: "155.00", ingredients: "Cinzano To Spritz, Frangelico, Agua Mineral, Ferrero Rocher" },
    { name: "Paloma", quantity: "180 ml", price: "155.00", ingredients: "Sal, Jose cuervo tradicional, Jugo de toronja, Jugo de limón verde, Jarabe natural, Agua mineral, Rodaja de toronja" },
    { name: "Side car", quantity: "112.5 ml", price: "175.00", ingredients: "Azúcar, Martel V.S., Controy, Jugo de limón verde, Jarabe natural" },
    { name: "Aperol spritz", quantity: "127 ml", price: "175.00", ingredients: "Cinzano To Spritz, Aperol, Agua Mineral, Rodaja de Naranja" },
    { name: "St germain spritz", quantity: "127.5 ml", price: "175.00", ingredients: "Cinzano To Spritz, St Germain, Agua Mineral, Punta De Romero, Pimienta Rosa Molida" },
    { name: "Old fashioned", quantity: "75 ml", price: "220.00", ingredients: "Bitter de angostura, Jim beam white, Jarabe natural, Cascara de naranja" },
    { name: "Pink gin", quantity: "60 ml", price: "220.00", ingredients: "Beefetear, Bitter de Angostura, Cascara de Limón Amarillo" },
    { name: "Manhattan dulce", quantity: "82.5 ml", price: "220.00", ingredients: "Jim bean white, Bitter de angostura, Vermut dulce, Cereza" },
    { name: "Manhattan seco", quantity: "82.5 ml", price: "220.00", ingredients: "Jim beam white, Bitter de angostura, Vermut seco, Cascara de limon amarillo" },
    { name: "Horses neck", quantity: "180 ml", price: "220.00", ingredients: "Jim beam white, Bitter de angostura, Ginger ale, Espiral de limon amarillo" },
    { name: "Manhattan perfecto", quantity: "90 ml", price: "220.00", ingredients: "Jim beam white, Bitter de angostura, Vermut dulce, Vermut seco, Cereza, Cascara de limon amarillo" },
    { name: "Rob roy", quantity: "82.5 ml", price: "220.00", ingredients: "J.W. red label, Vermut dulce, Bitter de angostura, Cereza" },
    { name: "Whiskey sour", quantity: "120 ml", price: "220.00", ingredients: "Bitter de angostura, Clara de huevo, Jim beam white, Jugo de limón amarillo, Jarabe natural, Cascara de naranja, Cereza" },
    { name: "Amaretto sour", quantity: "120 ml", price: "250.00", ingredients: "Bitter de angostura, Clara de huevo, Dissarono, Jugo de limón amarillo, Jarabe natural, Gajo de limón amarillo, Cereza" },
    { name: "Midori sour", quantity: "120 ml", price: "250.00", ingredients: "Bitter de angostura, Clara de huevo, Midori, Jugo de limón amarillo, Jarabe natural, Gajo de limón amarillo, Cereza" },
    { name: "New york sour", quantity: "150 ml", price: "250.00", ingredients: "Bitter de angostura, Clara de huevo, Jim beam white, Jugo de limón amarillo, Jarabe natural, Altozano ensamble crianza, Cascara de naranja, Cereza" },
    { name: "Carajillo con Kalua", quantity: "120 ml", price: "135.00", ingredients: "Kahlua, Expresso, Granos de Café" },
  ];
  
export const preparadosItems = [
    { name: "Cerveza sunrise", quantity: "150 ml", price: "120.00", ingredients: "Chamoy De Sabor, Tajin, Jose Cuervo Tradicional, Granadina, Jugo De Limón Verde, Heineken" },
    { name: "Cerveza hawaian", quantity: "150 ml", price: "150.00", ingredients: "Chamoy De Sabor, Tajin, Bacardi Blanco, Jugo De Piña, Flamingo De Curazao, Jugo De Limón Verde, Heineken" },
    { name: "Chela azulita", quantity: "150 ml", price: "120.00", ingredients: "Chamoy De Sabor, Tajin, Jose Cuervo Tradicional, Flamingo De Curazao, Jugo De Limón Verde, Sprite, Gomita De Tiburones" },
    { name: "Chelada", quantity: "15 ml", price: "15.00", ingredients: "Sal, Jugo De Limón Verde" },
    { name: "Michelada", quantity: "45 ml", price: "15.00", ingredients: "" },
    { name: "Cubana", quantity: "105 ml", price: "20.00", ingredients: "Jugo De Limón Verde, Petroleo, Tajin" },
    { name: "Clamato", quantity: "105 ml", price: "25.00", ingredients: "Jugo De Limón Verde, Petroleo, Clamato, Tajin" },
    { name: "Cerveza camarones", quantity: "105 ml", price: "75.00", ingredients: "Jugo De Limón Verde, Petroleo, Clamato, Tajin, Camarones" },
    { name: "Cerveza de ostiones", quantity: "105 ml", price: "75.00", ingredients: "Jugo De Limón Verde, Petroleo, Clamato, Tajin, Ostiones" },
];
  
export const snackItems = [
    { name: "Alitas", quantity: "300grs", accompaniment: "apio, zanahoria y aderezo blue cheese", price: "165.00" },
    { name: "Boneless", quantity: "200grs", accompaniment: "apio, zanahoria y aderezo blue cheese", price: "145.00" },
    { name: "Papas a la parmesana", quantity: "", accompaniment: "c/trufa", price: "108.00" },
];

export const sodaItems = [
    { name: "Agua enbotellada 355 ml", price: "20.00" },
    { name: "Sidral 355 ml", price: "30.00" },
    { name: "Coca cola 355 ml", price: "30.00" },
    { name: "Coca cola light 355 ml", price: "30.00" },
    { name: "Fresca 355 ml", price: "30.00" },
    { name: "Valle frut mango 355 ml", price: "30.00" },
    { name: "Valle frut guayaba 355 ml", price: "30.00" },
    { name: "Ciel mineral 600 ml", price: "35.00" },
    { name: "Topo chico 355 ml", price: "35.00" },
];

export const beerItems = [
    { name: "XX ambar", quantity: "325 ml", price: "55.00" },
    { name: "XX lager", quantity: "325 ml", price: "55.00" },
    { name: "Amstel ultra", quantity: "355 ml", price: "55.00" },
    { name: "Bohemia oscura", quantity: "355 ml", price: "55.00" },
    { name: "Heineken normal", quantity: "355 ml", price: "55.00" },
    { name: "Heineken zero", quantity: "355 ml", price: "55.00" },
    { name: "Corona", quantity: "355 ml", price: "55.00" },
    { name: "Victoria", quantity: "355 ml", price: "55.00" },
    { name: "Modelo especial", quantity: "355 ml", price: "55.00" },
    { name: "Tarro chico de barril", quantity: "300 ml", price: "70.00" },
    { name: "Tarro grande de barril", quantity: "1000 ml", price: "125.00" },
];
    
export const beverageItems = [
    { name: "Tanqueray", category: "Ginebra", priceGlass: "120.00", priceBottle: "1,100.00" },
    { name: "Hendrick's", category: "Ginebra", priceGlass: "150.00", priceBottle: "1,900.00" },
    { name: "Smirnoff", category: "Vodka", priceGlass: "95.00", priceBottle: "1,100.00" },
    { name: "Smirnoff tamarindo", category: "Vodka", priceGlass: "105.00", priceBottle: "1,100.00" },
    { name: "Absolut", category: "Vodka", priceGlass: "110.00", priceBottle: "1,300.00" },
    { name: "Grey goose", category: "Vodka", priceGlass: "145.00", priceBottle: "2,300.00" },
    { name: "Herradura blanco", category: "Tequila", priceGlass: "115.00", priceBottle: "1,400.00" },
    { name: "Herradura reposado", category: "Tequila", priceGlass: "120.00", priceBottle: "1,900.00" },
    { name: "Dobel diamante", category: "Tequila", priceGlass: "160.00", priceBottle: "2,300.00" },
    { name: "Don julio 70", category: "Tequila", priceGlass: "150.00", priceBottle: "2,500.00" },
    { name: "Don julio blanco", category: "Tequila", priceGlass: "140.00", priceBottle: "2,100.00" },
    { name: "Herradura añejo", category: "Tequila", priceGlass: "145.00", priceBottle: "1,600.00" },
    { name: "Hornitos añejo", category: "Tequila", priceGlass: "130.00", priceBottle: "1,900.00" },
    { name: "Jose cuervo tradicional", category: "Tequila", priceGlass: "100.00", priceBottle: "1,400.00" },
    { name: "Montelobos espadín", category: "Mezcal", priceGlass: "135.00", priceBottle: "1,550.00" },
    { name: "400 conejos joven", category: "Mezcal", priceGlass: "120.00", priceBottle: "1,350.00" },
    { name: "Mono araña", category: "Mezcal", priceGlass: "100.00", priceBottle: "1,200.00" },
    { name: "Matusalem plata", category: "Ron", priceGlass: "120.00", priceBottle: "1,400.00" },
    { name: "Havana 3", category: "Ron", priceGlass: "105.00", priceBottle: "1,100.00" },
    { name: "Havana 7", category: "Ron", priceGlass: "115.00", priceBottle: "1,600.00" },
    { name: "Bacardí añejo", category: "Ron", priceGlass: "105.00", priceBottle: "1,200.00" },
    { name: "Bacardí solera", category: "Ron", priceGlass: "105.00", priceBottle: "1,700.00" },
    { name: "Malibu", category: "Ron", priceGlass: "115.00", priceBottle: "1,200.00" },
    { name: "Bacardi blanco", category: "Ron", priceGlass: "90.00", priceBottle: "1,400.00" },
    { name: "Red label", category: "Whisky", priceGlass: "110.00", priceBottle: "1,500.00" },
    { name: "The glenlivet 12", category: "Whisky", priceGlass: "165.00", priceBottle: "2,800.00" },
    { name: "Macallan 12", category: "Whisky", priceGlass: "180.00", priceBottle: "4,200.00" },
    { name: "Black label", category: "Whisky", priceGlass: "130.00", priceBottle: "2,700.00" },
    { name: "Jim beam white", category: "Whisky Bourbon", priceGlass: "105.00", priceBottle: "1,400.00" },
    { name: "Woodford reserve", category: "Whisky Bourbon", priceGlass: "145.00", priceBottle: "2,400.00" },
    { name: "Bulleit bourbon", category: "Whisky Bourbon", priceGlass: "135.00", priceBottle: "1,900.00" },
    { name: "Martell v.s.", category: "Cognac", priceGlass: "155.00", priceBottle: "2,300.00" },
    { name: "Torres 10", category: "Brandy", priceGlass: "115.00", priceBottle: "1,500.00" },
    { name: "Sambuca vaccari nero", category: "Anis", priceGlass: "120.00", priceBottle: null },
    { name: "Anís de cadenas", category: "Anis", priceGlass: "115.00", priceBottle: null },
    { name: "Aperol", category: "Aperitivo", priceGlass: "110.00", priceBottle: null },
    { name: "Martini seco", category: "Aperitivo", priceGlass: "105.00", priceBottle: null },
    { name: "Martini rosso", category: "Aperitivo", priceGlass: "105.00", priceBottle: null },
    { name: "Disaronno amaretto", category: "Licor", priceGlass: "135.00", priceBottle: null },
    { name: "Baileys", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Jagermeister", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Fernet menta", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Kahlua", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Flamingo cereza", category: "Licor", priceGlass: "95.00", priceBottle: null },
    { name: "Flamingo durazno", category: "Licor", priceGlass: "95.00", priceBottle: null },
    { name: "Flamingo curacao", category: "Licor", priceGlass: "95.00", priceBottle: null },
    { name: "Porto ferreira tawny", category: "Licor", priceGlass: "140.00", priceBottle: null },
    { name: "Chartreuse de hierbas verde", category: "Licor", priceGlass: "185.00", priceBottle: null },
    { name: "Midori de melón", category: "Licor", priceGlass: "135.00", priceBottle: null },
    { name: "Licor de naranja controy", category: "Licor", priceGlass: "110.00", priceBottle: null },
    { name: "Cinzano to spritz dry", category: "Licor", priceGlass: "110.00", priceBottle: null },
    { name: "Campari vermouth", category: "Licor", priceGlass: "110.00", priceBottle: null },
    { name: "Licor 43", category: "Licor", priceGlass: "135.00", priceBottle: null },
    { name: "Branca menta de hierbas", category: "Licor", priceGlass: "120.00", priceBottle: null },
    { name: "Angostura de hierbas", category: "Licor", priceGlass: "140.00", priceBottle: null },
    { name: "St-Germain", category: "Licor", priceGlass: "160.00", priceBottle: null },
    { name: "Frangelico", category: "Licor", priceGlass: "135.00", priceBottle: null }
];
