export const breakfastItems = [
    { name: "Chilaquiles verdes", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "90.00", pricePackage: "120.00" },
    { name: "Chilaquiles verdes con huevo", quantity: "100 grs + 120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "110.00", pricePackage: "140.00" },
    { name: "Chilaquiles verdes con pollo", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "120.00", pricePackage: "150.00" },
    { name: "Chilaquiles verdes con aguja norteña", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "150.00", pricePackage: "180.00" },
    { name: "Chilaquiles verdes con arrachera marinada", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles verdes con rib eye", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles verdes con new york", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles verdes con sirloin", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "90.00", pricePackage: "120.00" },
    { name: "Chilaquiles rojos con huevo", quantity: "100 grs + 120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "110.00", pricePackage: "140.00" },
    { name: "Chilaquiles rojos con pollo", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "120.00", pricePackage: "150.00" },
    { name: "Chilaquiles rojos con aguja norteña", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "150.00", pricePackage: "180.00" },
    { name: "Chilaquiles rojos con arrachera marinada", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos con rib eye", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos con new york", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Chilaquiles rojos con sirloin", quantity: "100 grs + 100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Enchiladas verdes con pollo", quantity: "160 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "116.00", pricePackage: "146.00" },
    { name: "Enchiladas verdes con huevo", quantity: "120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "126.00", pricePackage: "156.00" },
    { name: "Enchiladas verdes con aguja norteña", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "152.00", pricePackage: "182.00" },
    { name: "Enchiladas verdes con arrachera marinada", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas verdes con rib eye", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas verdes con new york", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas verdes con sirloin", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con pollo", quantity: "160 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "116.00", pricePackage: "146.00" },
    { name: "Enchiladas rojas con huevo", quantity: "120 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "126.00", pricePackage: "156.00" },
    { name: "Enchiladas rojas con aguja norteña", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "152.00", pricePackage: "182.00" },
    { name: "Enchiladas rojas con arrachera marinada", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con rib eye", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con new york", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas rojas con sirloin", quantity: "100 grs", accompaniment: "cebolla, cilantro, crema, queso panela", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Enchiladas suizas con pollo", quantity: "160 grs", accompaniment: "cebolla, cilantro, crema, queso panela, queso", priceNormal: "135.00", pricePackage: "165.00" },
    { name: "Enchiladas veracruzanas", quantity: "180 grs", accompaniment: "chorizo, cilantro, crema, queso panela, aguacate", priceNormal: "115.00", pricePackage: "145.00" },
    { name: "Huevos divorciados", quantity: "120 grs", accompaniment: "frijol, crema, queso panela, cilantro", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Huevos a la mexicana", quantity: "120 grs", accompaniment: "frijol, ensalada, tortillas", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Huevos rancheros", quantity: "120 grs", accompaniment: "jamon, frijoles, tortillas", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Huevos revueltos", quantity: "120 grs", accompaniment: "frijol, ensalada, tortillas. con jamon 70grs, tocino 90grs, o chorizo 90grs", priceNormal: "89.00", pricePackage: "119.00" },
  ];
  
  export const entranceItems = [
    { name: "Queso fundido", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "125.00" },
    { name: "Queso fundido con arrachera", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "165.00" },
    { name: "Queso fundido con aguja norteña", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "165.00" },
    { name: "Queso fundido con rib eye", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "185.00" },
    { name: "Queso fundido con new york", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "185.00" },
    { name: "Queso fundido con sirloin", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "185.00" },
    { name: "Guacamole", accompaniment: "cebolla cambray, chile toreado, tortillas", price: "145.00" },
    { name: "Pescadilla", quantity: "3 pz 500 grs", accompaniment: "aguacate, limon", price: "83.00" },
    { name: "Sopes", quantity: "", accompaniment: "", price: "" },
    { name: "Huaraches", quantity: "", accompaniment: "", price: "" },
  ];

  export const coldEntranceItems = [
    { name: "Cóctel de camaron chico", quantity: "80 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "95.00" },
    { name: "Cóctel de camaron grande", quantity: "140 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "145.00" },
    { name: "Cóctel de campechano chico", quantity: "80 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "95.00" },
    { name: "Cóctel de campachano grande", quantity: "140 grs", accompaniment: "cebolla, jitomate, cilantro, aguacate", price: "145.00" },
    { name: "Tostada de atun", quantity: "1 pz 80 grs", accompaniment: "cebolla, jitomate, aguacate", price: "95.00" },
    { name: "Tostada de pescado", quantity: "1 pz 60 grs", accompaniment: "cebolla, jitomate, aguacate", price: "95.00" },
    { name: "Tostada de pulpo", quantity: "1 pz 60 grs", accompaniment: "cebolla, jitomate, aguacate", price: "125.00" },
    { name: "Tostada de camaron", quantity: "1 pz 60 grs", accompaniment: "cebolla, jitomate, aguacate", price: "125.00" },
    { name: "Aguachile rojo", quantity: "", accompaniment: "", price: "" },
    { name: "Aguachile negro", quantity: "", accompaniment: "", price: "" },
    { name: "Aguachile verde", quantity: "", accompaniment: "", price: "" },
  ];
  
  export const foodItems = [
    { name: "Camarones momia", quantity: "150 grs", accompaniment: "ensalada de la casa", price: "225.00" },
    { name: "Atun a la parrilla", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "213.00" },
    { name: "Salmon a la parrilla", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "245.00" },
    { name: "Ensalada de frutos rojos", quantity: "180 grs", accompaniment: "aderezo de la casa, queso cabra", price: "165.00" },
    { name: "Ensalada de melon", quantity: "200 grs", accompaniment: "queso panela", price: "115.00" },
    { name: "Arrachera", quantity: "200 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "295.00" },
    { name: "Aguja norteña", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "295.00" },
    { name: "Rib eye", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "345.00" },
    { name: "New york", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "345.00" },
    { name: "Sirloin", quantity: "250 grs", accompaniment: "papas a la francesa, cebollas cambray, nopal baby, chiles toreados", price: "345.00" },
    { name: "Pechuga al limon", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "165.00" },
    { name: "Pechuga al chipotle", quantity: "200 grs", accompaniment: "ensalada de la casa, arroz amarillo", price: "185.00" },
    { name: "Tacos de arrachera", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "58.00" },
    { name: "Tacos de aguja norteña", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "58.00" },
    { name: "Tacos de rib eye", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "68.00" },
    { name: "Tacos de new york", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "68.00" },
    { name: "Tacos de sirloin", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "68.00" },
    { name: "Tacos de pechuga al limon", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "49.00" },
    { name: "Tacos de pechuga al chipotle", quantity: "1 pz 60 grs", accompaniment: "papas al oregano, chiles toreados, nopal baby, guacamole", price: "49.00" },
    { name: "Hamburguesa clasica", quantity: "1 pz 180 grs", accompaniment: "queso americano. lechuga, jitomate, cebolla, tocino, papas a", price: "175.00" },
    { name: "Hamburguesa doble carne", quantity: "1 pz 300 grs", accompaniment: "queso americano. lechuga, jitomate, cebolla, tocino, papas a", price: "195.00" },
    { name: "Hamburguesa tocinito", quantity: "1 pz 180 grs", accompaniment: "queso chihuahua. lechuga, jitomate, cebolla, tocino, papas a la francesa", price: "185.00" },
    { name: "Hamburguesa queso + queso", quantity: "1 pz 180 grs", accompaniment: "queso chihuahua, queso oaxaca. lechuga, jitomate, cebolla, papas", price: "185.00" },
    { name: "Hamburguesa de la granja", quantity: "1 pz 300 grs", accompaniment: "queso chihuahua, lechuga, jitomate, cebolla, huevo, papas a la francesa", price: "185.00" },
    { name: "Hamburguesa mar y tierra", quantity: "1 pz 240 grs", accompaniment: "queso oaxaca, lechuga, jitomate, cebolla, papas a la francesa", price: "195.00" },
    { name: "Hamburguesa la de casa", quantity: "1 pz 150 grs Arrachera", accompaniment: "queso oaxaca, queso chihuahua, lechuga, jitomate, cebolla", price: "228.00" },
    { name: "Hamburguesa de pollo", quantity: "1 pz 180 grs", accompaniment: "queso americano, lechuga, jitomate, cebolla, salsa bufalo, papas", price: "185.00" }
];

  export const drinkItems = [
    { name: "Kamikaze", quantity: "37.5 ml", price: "65.00" },
    { name: "Lemon drop", quantity: "45 ml", price: "65.00" },
    { name: "B52", quantity: "45 ml", price: "65.00" },
    { name: "Black russian", quantity: "67.5 ml", price: "65.00" },
    { name: "White russian", quantity: "150 ml", price: "65.00" },
    { name: "Daiquiri clasico", quantity: "105 ml", price: "65.00" },
    { name: "Orgasm", quantity: "90 ml", price: "65.00" },
    { name: "Caipiroska", quantity: "82.5 ml", price: "65.00" },
    { name: "Godmother", quantity: "60 ml", price: "65.00" },
    { name: "Screaming orgasm", quantity: "105 ml", price: "65.00" },
    { name: "Tinto de verano", quantity: "150 ml", price: "65.00" },
    { name: "Vodka & tonic", quantity: "180 ml", price: "65.00" },
    { name: "Expresso martini", quantity: "127.5 ml", price: "90.00" },
    { name: "Cuba libre", quantity: "180 ml", price: "90.00" },
    { name: "Cubata", quantity: "180 ml", price: "90.00" },
    { name: "Fidel castro", quantity: "180 ml", price: "90.00" },
    { name: "Colorado bulldog", quantity: "150 ml", price: "90.00" },
    { name: "Godfather", quantity: "60 ml", price: "90.00" },
    { name: "Cape codder", quantity: "180 ml", price: "90.00" },
    { name: "Margarita clásica", quantity: "112.5 ml", price: "90.00" },
    { name: "Woo woo", quantity: "180 ml", price: "90.00" },
    { name: "White lady", quantity: "112.5 ml", price: "90.00" },
    { name: "Boulevardier", quantity: "90 ml", price: "90.00" },
    { name: "Pink lady", quantity: "120 ml", price: "90.00" },
    { name: "Americano", quantity: "90 ml", price: "90.00" },
    { name: "Mojito", quantity: "180 ml", price: "90.00" },
    { name: "Wet martini", quantity: "75 ml", price: "90.00" },
    { name: "Negroni", quantity: "90 ml", price: "90.00" },
    { name: "Gin & tonic", quantity: "180 ml", price: "110.00" },
    { name: "Gin basil smash", quantity: "105 ml", price: "110.00" },
    { name: "Southside", quantity: "105 ml", price: "110.00" },
    { name: "Mezcaloni", quantity: "90 ml", price: "110.00" },
    { name: "Dry martini", quantity: "60 ml", price: "110.00" },
    { name: "Hemingway daiquiri", quantity: "112.5 ml", price: "110.00" },
    { name: "Dirty martini", quantity: "90 ml", price: "110.00" },
    { name: "Cosmopolitan", quantity: "112.5 ml", price: "110.00" },
    { name: "AMF", quantity: "180 ml", price: "110.00" },
    { name: "Tommy's margarita", quantity: "135 ml", price: "110.00" },
    { name: "Bull", quantity: "150 ml", price: "110.00" },
    { name: "Lychburg limonade", quantity: "180 ml", price: "110.00" },
    { name: "Negroni sbagliato", quantity: "90 ml", price: "125.00" },
    { name: "Carajillo", quantity: "120 ml", price: "125.00" },
    { name: "Long island iced tea", quantity: "180 ml", price: "125.00" },
    { name: "Clover club", quantity: "120 ml", price: "125.00" },
    { name: "Mezcalita", quantity: "105 ml", price: "125.00" },
    { name: "John collins", quantity: "180 ml", price: "125.00" },
    { name: "Mimosa", quantity: "240 ml", price: "125.00" },
    { name: "Back room", quantity: "90 ml", price: "125.00" },
    { name: "Tequila sunrise", quantity: "180 ml", price: "125.00" },
    { name: "Bloody mari", quantity: "165 ml", price: "135.00" },
    { name: "Tom collins", quantity: "180 ml", price: "135.00" },
    { name: "Beverly hills iced tea", quantity: "180 ml", price: "135.00" },
    { name: "Long beach iced tea", quantity: "180 ml", price: "135.00" },
    { name: "Piña colada", quantity: "180 ml", price: "135.00" },
    { name: "Sex on the beach", quantity: "180 ml", price: "135.00" },
    { name: "Pitufo", quantity: "180 ml", price: "135.00" },
    { name: "Red snapper", quantity: "165 ml", price: "155.00" },
    { name: "Last word", quantity: "90 ml", price: "155.00" },
    { name: "Frangelico spritz", quantity: "127.5 ml", price: "155.00" },
    { name: "Paloma", quantity: "180 ml", price: "155.00" },
    { name: "Side car", quantity: "112.5 ml", price: "175.00" },
    { name: "Aperol spritz", quantity: "127 ml", price: "175.00" },
    { name: "St germain spritz", quantity: "127.5 ml", price: "175.00" },
    { name: "Old fashioned", quantity: "75 ml", price: "220.00" },
    { name: "Pink gin", quantity: "60 ml", price: "220.00" },
    { name: "Manhattan dulce", quantity: "82.5 ml", price: "220.00" },
    { name: "Manhattan seco", quantity: "82.5 ml", price: "220.00" },
    { name: "Horses neck", quantity: "180 ml", price: "220.00" },
    { name: "Manhattan perfecto", quantity: "90 ml", price: "220.00" },
    { name: "Rob roy", quantity: "82.5 ml", price: "220.00" },
    { name: "Whiskey sour", quantity: "120 ml", price: "220.00" },
    { name: "Amaretto sour", quantity: "120 ml", price: "250.00" },
    { name: "Midori sour", quantity: "120 ml", price: "250.00" },
    { name: "New york sour", quantity: "150 ml", price: "250.00" },
    { name: "Carajillo con kalua", quantity: "120 ml", price: "135.00" },
  ];
  
export const preparadosItems = [
    { name: "Cerveza sunrise", quantity: "150 ml", price: "120.00" },
    { name: "Cerveza hawaian", quantity: "150 ml", price: "150.00" },
    { name: "Chela azulita", quantity: "150 ml", price: "120.00" },
    { name: "Chelada", quantity: "15 ml", price: "15.00" },
    { name: "Michelada", quantity: "45 ml", price: "15.00" },
    { name: "Cubana", quantity: "105 ml", price: "20.00" },
    { name: "Cerveza camarones", quantity: "105 ml", price: "75.00" },
    { name: "Cerveza de ostiones", quantity: "105 ml", price: "75.00" },
];
  
export const snackItems = [
    { name: "Alitas", quantity: "300grs", accompaniment: "apio, zanahoria y aderezo blue cheese", price: "165.00" },
    { name: "Boneless", quantity: "200grs", accompaniment: "apio, zanahoria y aderezo blue cheese", price: "145.00" },
    { name: "Papas a la parmesana", quantity: "", accompaniment: "c/trufa", price: "108.00" },
];

export const sodaItems = [
    { name: "Agua enbotellada 355 ml", price: "20.00" },
    { name: "Sidral 355 ml", price: "30.00" },
    { name: "Coca cola 355 ml", price: "30.00" },
    { name: "Coca cola light 355 ml", price: "30.00" },
    { name: "Fresca 355 ml", price: "30.00" },
    { name: "Valle frut mango 355 ml", price: "30.00" },
    { name: "Valle frut guayaba 355 ml", price: "30.00" },
    { name: "Ciel mineral 600 ml", price: "35.00" },
    { name: "Topo chico 355 ml", price: "35.00" },
];

export const beerItems = [
    { name: "XX ambar", quantity: "325 ml", price: "55.00" },
    { name: "XX lager", quantity: "325 ml", price: "55.00" },
    { name: "Amstel ultra", quantity: "355 ml", price: "55.00" },
    { name: "Bohemia oscura", quantity: "355 ml", price: "55.00" },
    { name: "Heineken normal", quantity: "355 ml", price: "55.00" },
    { name: "Heineken zero", quantity: "355 ml", price: "55.00" },
    { name: "Corona", quantity: "355 ml", price: "55.00" },
    { name: "Victoria", quantity: "355 ml", price: "55.00" },
    { name: "Modelo especial", quantity: "355 ml", price: "55.00" },
    { name: "Tarro chico de barril", quantity: "300 ml", price: "70.00" },
    { name: "Tarro grande de barril", quantity: "1000 ml", price: "125.00" },
];
    
export const beverageItems = [
    { name: "Tanqueray", category: "Ginebra", priceGlass: "120.00", priceBottle: "1,100.00" },
    { name: "Hendrick's", category: "Ginebra", priceGlass: "150.00", priceBottle: "1,900.00" },
    { name: "Smirnoff", category: "Vodka", priceGlass: "95.00", priceBottle: "1,100.00" },
    { name: "Smirnoff Tamarindo", category: "Vodka", priceGlass: "105.00", priceBottle: "1,100.00" },
    { name: "Absolut", category: "Vodka", priceGlass: "110.00", priceBottle: "1,300.00" },
    { name: "Grey Goose", category: "Vodka", priceGlass: "145.00", priceBottle: "2,300.00" },
    { name: "Herradura Blanco", category: "Tequila", priceGlass: "115.00", priceBottle: "1,400.00" },
    { name: "Herradura Reposado", category: "Tequila", priceGlass: "120.00", priceBottle: "1,900.00" },
    { name: "Dobel Diamante", category: "Tequila", priceGlass: "160.00", priceBottle: "2,300.00" },
    { name: "Don Julio 70", category: "Tequila", priceGlass: "150.00", priceBottle: "2,500.00" },
    { name: "Don Julio Blanco", category: "Tequila", priceGlass: "140.00", priceBottle: "2,100.00" },
    { name: "Herradura Añejo", category: "Tequila", priceGlass: "145.00", priceBottle: "1,600.00" },
    { name: "Hornitos Añejo", category: "Tequila", priceGlass: "130.00", priceBottle: "1,900.00" },
    { name: "Jose Cuervo Tradicional", category: "Tequila", priceGlass: "100.00", priceBottle: "1,400.00" },
    { name: "Montelobos Espadín", category: "Mezcal", priceGlass: "135.00", priceBottle: "1,550.00" },
    { name: "400 Conejos Joven", category: "Mezcal", priceGlass: "120.00", priceBottle: "1,350.00" },
    { name: "Mono Araña", category: "Mezcal", priceGlass: "100.00", priceBottle: "1,200.00" },
    { name: "Matusalem Plata", category: "Ron", priceGlass: "120.00", priceBottle: "1,400.00" },
    { name: "Havana 3", category: "Ron", priceGlass: "105.00", priceBottle: "1,100.00" },
    { name: "Havana 7", category: "Ron", priceGlass: "115.00", priceBottle: "1,600.00" },
    { name: "Bacardí Añejo", category: "Ron", priceGlass: "105.00", priceBottle: "1,200.00" },
    { name: "Bacardí Solera", category: "Ron", priceGlass: "105.00", priceBottle: "1,700.00" },
    { name: "Malibu", category: "Ron", priceGlass: "115.00", priceBottle: "1,200.00" },
    { name: "Bacardi Blanco", category: "Ron", priceGlass: "90.00", priceBottle: "1,400.00" },
    { name: "Red Label", category: "Whisky", priceGlass: "110.00", priceBottle: "1,500.00" },
    { name: "The Glenlivet 12", category: "Whisky", priceGlass: "165.00", priceBottle: "2,800.00" },
    { name: "Macallan 12", category: "Whisky", priceGlass: "180.00", priceBottle: "4,200.00" },
    { name: "Black Label", category: "Whisky", priceGlass: "130.00", priceBottle: "2,700.00" },
    { name: "Jim Beam White", category: "Whisky Bourbon", priceGlass: "105.00", priceBottle: "1,400.00" },
    { name: "Woodford Reserve", category: "Whisky Bourbon", priceGlass: "145.00", priceBottle: "2,400.00" },
    { name: "Bulleit Bourbon", category: "Whisky Bourbon", priceGlass: "135.00", priceBottle: "1,900.00" },
    { name: "Martell V.S.", category: "Cognac", priceGlass: "155.00", priceBottle: "2,300.00" },
    { name: "Torres 10", category: "Brandy", priceGlass: "115.00", priceBottle: "1,500.00" },
    { name: "Sambuca Vaccari Nero", category: "Anis", priceGlass: "120.00", priceBottle: null },
    { name: "Anís de Cadenas", category: "Anis", priceGlass: "115.00", priceBottle: null },
    { name: "Aperol", category: "Aperitivo", priceGlass: "110.00", priceBottle: null },
    { name: "Martini Seco", category: "Aperitivo", priceGlass: "105.00", priceBottle: null },
    { name: "Martini Rosso", category: "Aperitivo", priceGlass: "105.00", priceBottle: null },
    { name: "Disaronno Amaretto", category: "Licor", priceGlass: "135.00", priceBottle: null },
    { name: "Baileys", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Jagermeister", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Fernet Menta", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Kahlua", category: "Licor", priceGlass: "115.00", priceBottle: null },
    { name: "Flamingo Cereza", category: "Licor", priceGlass: "95.00", priceBottle: null },
    { name: "Flamingo Durazno", category: "Licor", priceGlass: "95.00", priceBottle: null },
    { name: "Flamingo Curacao", category: "Licor", priceGlass: "95.00", priceBottle: null },
    { name: "Porto Ferreira Tawny", category: "Licor", priceGlass: "140.00", priceBottle: null },
    { name: "Chartreuse de Hierbas Verde", category: "Licor", priceGlass: "185.00", priceBottle: null },
    { name: "Midori de Melón", category: "Licor", priceGlass: "135.00", priceBottle: null },
    { name: "Licor de Naranja Controy", category: "Licor", priceGlass: "110.00", priceBottle: null },
    { name: "Cinzano To Spritz Dry", category: "Licor", priceGlass: "110.00", priceBottle: null },
    { name: "Campari Vermouth", category: "Licor", priceGlass: "110.00", priceBottle: null },
    { name: "Licor 43", category: "Licor", priceGlass: "135.00", priceBottle: null },
    { name: "Branca Menta de Hierbas", category: "Licor", priceGlass: "120.00", priceBottle: null },
    { name: "Angostura de Hierbas", category: "Licor", priceGlass: "140.00", priceBottle: null },
    { name: "St-Germain", category: "Licor", priceGlass: "160.00", priceBottle: null },
    { name: "Frangelico", category: "Licor", priceGlass: "135.00", priceBottle: null }
];
