export const breakfastItemsEn = [
    { name: "Green chilaquiles", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "90.00", pricePackage: "120.00" },
    { name: "Green chilaquiles with egg", quantity: "100grs + 120grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "110.00", pricePackage: "140.00" },
    { name: "Green chilaquiles with chicken", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "120.00", pricePackage: "150.00" },
    { name: "Green chilaquiles with northern needle steak", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "150.00", pricePackage: "180.00" },
    { name: "Green chilaquiles with marinated arrachera", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Green chilaquiles with rib eye", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Green chilaquiles with new york", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Green chilaquiles with sirloin", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Red chilaquiles", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "90.00", pricePackage: "120.00" },
    { name: "Red chilaquiles with egg", quantity: "100grs + 120grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "110.00", pricePackage: "140.00" },
    { name: "Red chilaquiles with chicken", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "120.00", pricePackage: "150.00" },
    { name: "Red chilaquiles with northern needle steak", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "150.00", pricePackage: "180.00" },
    { name: "Red chilaquiles with marinated arrachera", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Red chilaquiles with rib eye", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Red chilaquiles with new york", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Red chilaquiles with sirloin", quantity: "100grs + 100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "160.00", pricePackage: "190.00" },
    { name: "Green enchiladas with chicken", quantity: "160grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "116.00", pricePackage: "146.00" },
    { name: "Green enchiladas with egg", quantity: "120grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "126.00", pricePackage: "156.00" },
    { name: "Green enchiladas with northern needle steak", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "152.00", pricePackage: "182.00" },
    { name: "Green enchiladas with marinated arrachera", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Green enchiladas with rib eye", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Green enchiladas with new york", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Green enchiladas with sirloin", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Red enchiladas with chicken", quantity: "160grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "116.00", pricePackage: "146.00" },
    { name: "Red enchiladas with egg", quantity: "120grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "126.00", pricePackage: "156.00" },
    { name: "Red enchiladas with northern needle steak", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "152.00", pricePackage: "182.00" },
    { name: "Red enchiladas with marinated arrachera", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Red enchiladas with rib eye", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Red enchiladas with new york", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Red enchiladas with sirloin", quantity: "100grs", accompaniment: "onion, cilantro, cream, panela cheese", priceNormal: "163.00", pricePackage: "193.00" },
    { name: "Swiss enchiladas with chicken", quantity: "160grs", accompaniment: "onion, cilantro, cream, panela cheese, cheese", priceNormal: "135.00", pricePackage: "165.00" },
    { name: "Veracruzanas enchiladas", quantity: "180grs", accompaniment: "chorizo, cilantro, cream, panela cheese, avocado", priceNormal: "115.00", pricePackage: "145.00" },
    { name: "Divorced eggs", quantity: "120grs", accompaniment: "beans, cream, panela cheese, cilantro", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Mexican style eggs", quantity: "120grs", accompaniment: "beans, salad, tortillas", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Rancheros eggs", quantity: "120grs", accompaniment: "ham, beans, tortillas", priceNormal: "89.00", pricePackage: "119.00" },
    { name: "Scrambled eggs", quantity: "120grs", accompaniment: "beans, salad, tortillas. with ham 70grs, bacon 90grs, or chorizo 90grs", priceNormal: "89.00", pricePackage: "119.00" },
  ];
  
  export const entranceItemsEn = [
    { name: "Melted cheese", accompaniment: "cambray onion, toreado chili, tortillas", price: "125.00" },
    { name: "Melted cheese with arrachera", accompaniment: "cambray onion, toreado chili, tortillas", price: "165.00" },
    { name: "Melted cheese with northern needle steak", accompaniment: "cambray onion, toreado chili, tortillas", price: "165.00" },
    { name: "Melted cheese with rib eye", accompaniment: "cambray onion, toreado chili, tortillas", price: "185.00" },
    { name: "Melted cheese with new york", accompaniment: "cambray onion, toreado chili, tortillas", price: "185.00" },
    { name: "Melted cheese with sirloin", accompaniment: "cambray onion, toreado chili, tortillas", price: "185.00" },
    { name: "Guacamole", accompaniment: "cambray onion, toreado chili, tortillas", price: "145.00" },
    { name: "Fish quesadilla", quantity: "3 pcs 500grs", accompaniment: "avocado, lemon", price: "83.00" },
    { name: "Sopes", quantity: "", accompaniment: "", price: "" },
    { name: "Huaraches", quantity: "", accompaniment: "", price: "" },
  ];

  export const coldEntranceItemsEn = [
    { name: "Small shrimp cocktail", quantity: "80grs", accompaniment: "onion, tomato, cilantro, avocado", price: "95.00" },
    { name: "Large shrimp cocktail", quantity: "140grs", accompaniment: "onion, tomato, cilantro, avocado", price: "145.00" },
    { name: "Small campechano cocktail", quantity: "80grs", accompaniment: "onion, tomato, cilantro, avocado", price: "95.00" },
    { name: "Large campechano cocktail", quantity: "140grs", accompaniment: "onion, tomato, cilantro, avocado", price: "145.00" },
    { name: "Tuna tostada", quantity: "1 pc 80grs", accompaniment: "onion, tomato, avocado", price: "95.00" },
    { name: "Fish tostada", quantity: "1 pc 60grs", accompaniment: "onion, tomato, avocado", price: "95.00" },
    { name: "Octopus tostada", quantity: "1 pc 60grs", accompaniment: "onion, tomato, avocado", price: "125.00" },
    { name: "Shrimp tostada", quantity: "1 pc 60grs", accompaniment: "onion, tomato, avocado", price: "125.00" },
    { name: "Red aguachile", quantity: "", accompaniment: "", price: "" },
    { name: "Black aguachile", quantity: "", accompaniment: "", price: "" },
    { name: "Green aguachile", quantity: "", accompaniment: "", price: "" },
  ];
  
  export const foodItemsEn = [
    { name: "Mummy shrimps", quantity: "150grs", accompaniment: "house salad", price: "225.00" },
    { name: "Grilled tuna", quantity: "200grs", accompaniment: "house salad, yellow rice", price: "213.00" },
    { name: "Grilled salmon", quantity: "200grs", accompaniment: "house salad, yellow rice", price: "245.00" },
    { name: "Red fruits salad", quantity: "180grs", accompaniment: "house dressing, goat cheese", price: "165.00" },
    { name: "Melon salad", quantity: "200grs", accompaniment: "panela cheese", price: "115.00" },
    { name: "Arrachera", quantity: "200grs", accompaniment: "french fries, cambray onions, baby nopal, toreados chilis", price: "295.00" },
    { name: "Northern needle steak", quantity: "250grs", accompaniment: "french fries, cambray onions, baby nopal, toreados chilis", price: "295.00" },
    { name: "Rib eye", quantity: "250grs", accompaniment: "french fries, cambray onions, baby nopal, toreados chilis", price: "345.00" },
    { name: "New york", quantity: "250grs", accompaniment: "french fries, cambray onions, baby nopal, toreados chilis", price: "345.00" },
    { name: "Sirloin", quantity: "250grs", accompaniment: "french fries, cambray onions, baby nopal, toreados chilis", price: "345.00" },
    { name: "Lemon chicken breast", quantity: "200grs", accompaniment: "house salad, yellow rice", price: "165.00" },
    { name: "Chipotle chicken breast", quantity: "200grs", accompaniment: "house salad, yellow rice", price: "185.00" },
    { name: "Arrachera tacos", quantity: "1 pc 60grs", accompaniment: "oregano potatoes, toreados chilis, baby nopal, guacamole", price: "58.00" },
    { name: "Northern needle steak tacos", quantity: "1 pc 60grs", accompaniment: "oregano potatoes, toreados chilis, baby nopal, guacamole", price: "58.00" },
    { name: "Rib eye tacos", quantity: "1 pc 60grs", accompaniment: "oregano potatoes, toreados chilis, baby nopal, guacamole", price: "68.00" },
    { name: "New york tacos", quantity: "1 pc 60grs", accompaniment: "oregano potatoes, toreados chilis, baby nopal, guacamole", price: "68.00" },
    { name: "Sirloin tacos", quantity: "1 pc 60grs", accompaniment: "oregano potatoes, toreados chilis, baby nopal, guacamole", price: "68.00" },
    { name: "Lemon chicken breast tacos", quantity: "1 pc 60grs", accompaniment: "oregano potatoes, toreados chilis, baby nopal, guacamole", price: "49.00" },
    { name: "Chipotle chicken breast tacos", quantity: "1 pc 60grs", accompaniment: "oregano potatoes, toreados chilis, baby nopal, guacamole", price: "49.00" },
    { name: "Classic burger", quantity: "1 pc 180grs", accompaniment: "american cheese. lettuce, tomato, onion, bacon, fries", price: "175.00" },
    { name: "Double meat burger", quantity: "1 pc 300grs", accompaniment: "american cheese. lettuce, tomato, onion, bacon, fries", price: "195.00" },
    { name: "Bacon burger", quantity: "1 pc 180grs", accompaniment: "chihuahua cheese. lettuce, tomato, onion, bacon, french fries", price: "185.00" },
    { name: "Cheese + cheese burger", quantity: "1 pc 180grs", accompaniment: "chihuahua cheese, oaxaca cheese. lettuce, tomato, onion, fries", price: "185.00" },
    { name: "Farm burger", quantity: "1 pc 300grs", accompaniment: "chihuahua cheese, lettuce, tomato, onion, egg, french fries", price: "185.00" },
    { name: "Surf and turf burger", quantity: "1 pc 240grs", accompaniment: "oaxaca cheese, lettuce, tomato, onion, french fries", price: "195.00" },
    { name: "House burger", quantity: "1 pc 150grs Arrachera", accompaniment: "oaxaca cheese, chihuahua cheese, lettuce, tomato, onion", price: "228.00" },
    { name: "Chicken burger", quantity: "1 pc 180grs", accompaniment: "american cheese, lettuce, tomato, onion, buffalo sauce, fries", price: "185.00" }
];

  export const drinkItemsEn = [
    { name: "Kamikaze", quantity: "37.5 ml", price: "65.00" },
    { name: "Lemon drop", quantity: "45 ml", price: "65.00" },
    { name: "B52", quantity: "45 ml", price: "65.00" },
    { name: "Black russian", quantity: "67.5 ml", price: "65.00" },
    { name: "White russian", quantity: "150 ml", price: "65.00" },
    { name: "Classic daiquiri", quantity: "105 ml", price: "65.00" },
    { name: "Orgasm", quantity: "90 ml", price: "65.00" },
    { name: "Caipiroska", quantity: "82.5 ml", price: "65.00" },
    { name: "Godmother", quantity: "60 ml", price: "65.00" },
    { name: "Screaming orgasm", quantity: "105 ml", price: "65.00" },
    { name: "Tinto de verano", quantity: "150 ml", price: "65.00" },
    { name: "Vodka & tonic", quantity: "180 ml", price: "65.00" },
    { name: "Espresso martini", quantity: "127.5 ml", price: "90.00" },
    { name: "Cuba libre", quantity: "180 ml", price: "90.00" },
    { name: "Cubata", quantity: "180 ml", price: "90.00" },
    { name: "Fidel castro", quantity: "180 ml", price: "90.00" },
    { name: "Colorado bulldog", quantity: "150 ml", price: "90.00" },
    { name: "Godfather", quantity: "60 ml", price: "90.00" },
    { name: "Cape codder", quantity: "180 ml", price: "90.00" },
    { name: "Classic margarita", quantity: "112.5 ml", price: "90.00" },
    { name: "Woo woo", quantity: "180 ml", price: "90.00" },
    { name: "White lady", quantity: "112.5 ml", price: "90.00" },
    { name: "Boulevardier", quantity: "90 ml", price: "90.00" },
    { name: "Pink lady", quantity: "120 ml", price: "90.00" },
    { name: "Americano", quantity: "90 ml", price: "90.00" },
    { name: "Mojito", quantity: "180 ml", price: "90.00" },
    { name: "Wet martini", quantity: "75 ml", price: "90.00" },
    { name: "Negroni", quantity: "90 ml", price: "90.00" },
    { name: "Gin & tonic", quantity: "180 ml", price: "110.00" },
    { name: "Gin basil smash", quantity: "105 ml", price: "110.00" },
    { name: "Southside", quantity: "105 ml", price: "110.00" },
    { name: "Mezcaloni", quantity: "90 ml", price: "110.00" },
    { name: "Dry martini", quantity: "60 ml", price: "110.00" },
    { name: "Hemingway daiquiri", quantity: "112.5 ml", price: "110.00" },
    { name: "Dirty martini", quantity: "90 ml", price: "110.00" },
    { name: "Cosmopolitan", quantity: "112.5 ml", price: "110.00" },
    { name: "AMF", quantity: "180 ml", price: "110.00" },
    { name: "Tommy's margarita", quantity: "135 ml", price: "110.00" },
    { name: "Bull", quantity: "150 ml", price: "110.00" },
    { name: "Lynchburg lemonade", quantity: "180 ml", price: "110.00" },
    { name: "Negroni sbagliato", quantity: "90 ml", price: "125.00" },
    { name: "Carajillo", quantity: "120 ml", price: "125.00" },
    { name: "Long island iced tea", quantity: "180 ml", price: "125.00" },
    { name: "Clover club", quantity: "120 ml", price: "125.00" },
    { name: "Mezcalita", quantity: "105 ml", price: "125.00" },
    { name: "John collins", quantity: "180 ml", price: "125.00" },
    { name: "Mimosa", quantity: "240 ml", price: "125.00" },
    { name: "Back room", quantity: "90 ml", price: "125.00" },
    { name: "Tequila sunrise", quantity: "180 ml", price: "125.00" },
    { name: "Bloody mary", quantity: "165 ml", price: "135.00" },
    { name: "Tom collins", quantity: "180 ml", price: "135.00" },
    { name: "Beverly hills iced tea", quantity: "180 ml", price: "135.00" },
    { name: "Long beach iced tea", quantity: "180 ml", price: "135.00" },
    { name: "Piña colada", quantity: "180 ml", price: "135.00" },
    { name: "Sex on the beach", quantity: "180 ml", price: "135.00" },
    { name: "Pitufo", quantity: "180 ml", price: "135.00" },
    { name: "Red snapper", quantity: "165 ml", price: "155.00" },
    { name: "Last word", quantity: "90 ml", price: "155.00" },
    { name: "Frangelico spritz", quantity: "127.5 ml", price: "155.00" },
    { name: "Paloma", quantity: "180 ml", price: "155.00" },
    { name: "Side car", quantity: "112.5 ml", price: "175.00" },
    { name: "Aperol spritz", quantity: "127 ml", price: "175.00" },
    { name: "St germain spritz", quantity: "127.5 ml", price: "175.00" },
    { name: "Old fashioned", quantity: "75 ml", price: "220.00" },
    { name: "Pink gin", quantity: "60 ml", price: "220.00" },
    { name: "Sweet manhattan", quantity: "82.5 ml", price: "220.00" },
    { name: "Dry manhattan", quantity: "82.5 ml", price: "220.00" },
    { name: "Horse's neck", quantity: "180 ml", price: "220.00" },
    { name: "Perfect manhattan", quantity: "90 ml", price: "220.00" },
    { name: "Rob roy", quantity: "82.5 ml", price: "220.00" },
    { name: "Whiskey sour", quantity: "120 ml", price: "220.00" },
    { name: "Amaretto sour", quantity: "120 ml", price: "250.00" },
    { name: "Midori sour", quantity: "120 ml", price: "250.00" },
    { name: "New york sour", quantity: "150 ml", price: "250.00" },
    { name: "Carajillo with kahlua", quantity: "120 ml", price: "135.00" },
  ];
  
export const preparadosItemsEn = [
    { name: "Sunrise beer", quantity: "150 ml", price: "120.00" },
    { name: "Hawaiian beer", quantity: "150 ml", price: "150.00" },
    { name: "Blue chela", quantity: "150 ml", price: "120.00" },
    { name: "Chelada", quantity: "15 ml", price: "15.00" },
    { name: "Michelada", quantity: "45 ml", price: "15.00" },
    { name: "Cubana", quantity: "105 ml", price: "20.00" },
    { name: "Shrimp beer", quantity: "105 ml", price: "75.00" },
    { name: "Oyster beer", quantity: "105 ml", price: "75.00" },
];
  
export const snackItemsEn = [
    { name: "Wings", quantity: "300grs", accompaniment: "celery, carrot and blue cheese dressing", price: "165.00" },
    { name: "Boneless", quantity: "200grs", accompaniment: "celery, carrot and blue cheese dressing", price: "145.00" },
    { name: "Parmesan fries", quantity: "", accompaniment: "w/truffle", price: "108.00" },
];

export const sodaItemsEn = [
    { name: "Bottled water 355 ml", price: "20.00" },
    { name: "Sidral 355 ml", price: "30.00" },
    { name: "Coca cola 355 ml", price: "30.00" },
    { name: "Coca cola light 355 ml", price: "30.00" },
    { name: "Fresca 355 ml", price: "30.00" },
    { name: "Valle frut mango 355 ml", price: "30.00" },
    { name: "Valle frut guava 355 ml", price: "30.00" },
    { name: "Ciel mineral 600 ml", price: "35.00" },
    { name: "Topo chico 355 ml", price: "35.00" },
];

export const beerItemsEn = [
    { name: "XX amber", quantity: "325 ml", price: "55.00" },
    { name: "XX lager", quantity: "325 ml", price: "55.00" },
    { name: "Amstel ultra", quantity: "355 ml", price: "55.00" },
    { name: "Bohemia dark", quantity: "355 ml", price: "55.00" },
    { name: "Heineken", quantity: "355 ml", price: "55.00" },
    { name: "Heineken zero", quantity: "355 ml", price: "55.00" },
    { name: "Corona", quantity: "355 ml", price: "55.00" },
    { name: "Victoria", quantity: "355 ml", price: "55.00" },
    { name: "Modelo especial", quantity: "355 ml", price: "55.00" },
    { name: "Small draft beer mug", quantity: "300 ml", price: "70.00" },
    { name: "Large draft beer mug", quantity: "1000 ml", price: "125.00" },
];

export const beverageItemsEn = [
    { name: "Tanqueray", category: "Gin", priceGlass: "120.00", priceBottle: "1,100.00" },
    { name: "Hendrick's", category: "Gin", priceGlass: "150.00", priceBottle: "1,900.00" },
    { name: "Smirnoff", category: "Vodka", priceGlass: "95.00", priceBottle: "1,100.00" },
    { name: "Smirnoff Tamarindo", category: "Vodka", priceGlass: "105.00", priceBottle: "1,100.00" },
    { name: "Absolut", category: "Vodka", priceGlass: "110.00", priceBottle: "1,300.00" },
    { name: "Grey Goose", category: "Vodka", priceGlass: "145.00", priceBottle: "2,300.00" },
    { name: "Herradura Blanco", category: "Tequila", priceGlass: "115.00", priceBottle: "1,400.00" },
    { name: "Herradura Reposado", category: "Tequila", priceGlass: "120.00", priceBottle: "1,900.00" },
    { name: "Dobel Diamante", category: "Tequila", priceGlass: "160.00", priceBottle: "2,300.00" },
    { name: "Don Julio 70", category: "Tequila", priceGlass: "150.00", priceBottle: "2,500.00" },
    { name: "Don Julio Blanco", category: "Tequila", priceGlass: "140.00", priceBottle: "2,100.00" },
    { name: "Herradura Añejo", category: "Tequila", priceGlass: "145.00", priceBottle: "1,600.00" },
    { name: "Hornitos Añejo", category: "Tequila", priceGlass: "130.00", priceBottle: "1,900.00" },
    { name: "Jose Cuervo Tradicional", category: "Tequila", priceGlass: "100.00", priceBottle: "1,400.00" },
    { name: "Montelobos Espadín", category: "Mezcal", priceGlass: "135.00", priceBottle: "1,550.00" },
    { name: "400 Conejos Joven", category: "Mezcal", priceGlass: "120.00", priceBottle: "1,350.00" },
    { name: "mono araña", category: "Mezcal", priceGlass: "100.00", priceBottle: "1,200.00" },
    { name: "Matusalem Plata", category: "Ron", priceGlass: "120.00", priceBottle: "1,400.00" },
    { name: "Havana 3", category: "Ron", priceGlass: "105.00", priceBottle: "1,100.00" },
    { name: "Havana 7", category: "Ron", priceGlass: "115.00", priceBottle: "1,600.00" },
    { name: "Bacardí Añejo", category: "Ron", priceGlass: "105.00", priceBottle: "1,200.00" },
    { name: "Bacardí Solera", category: "Ron", priceGlass: "105.00", priceBottle: "1,700.00" },
    { name: "Malibu", category: "Ron", priceGlass: "115.00", priceBottle: "1,200.00" },
    { name: "Bacardi bco", category: "Ron", priceGlass: "90.00", priceBottle: "1,400.00" },
    { name: "Red Label", category: "Whisky", priceGlass: "110.00", priceBottle: "1,500.00" },
    { name: "The Glenlivet 12", category: "Whisky", priceGlass: "165.00", priceBottle: "2,800.00" },
    { name: "Macallan 12", category: "Whisky", priceGlass: "180.00", priceBottle: "4,200.00" },
    { name: "Black Label", category: "Whisky", priceGlass: "130.00", priceBottle: "2,700.00" },
    { name: "Jim Beam White", category: "Whisky Bourbon", priceGlass: "105.00", priceBottle: "1,400.00" },
    { name: "Woodford Reserve", category: "Whisky Bourbon", priceGlass: "145.00", priceBottle: "2,400.00" },
    { name: "Bulleit Bourbon", category: "Whisky Bourbon", priceGlass: "135.00", priceBottle: "1,900.00" },
    { name: "Marttel V.S.", category: "Cognac", priceGlass: "155.00", priceBottle: "2,300.00" },
    { name: "Torres 10", category: "Brandy", priceGlass: "115.00", priceBottle: "1,500.00" },
    { name: "Sambuca Vaccari Nero", category: "Anise", priceGlass: "120.00", priceBottle: null },
    { name: "Anís De Cadenas", category: "Anise", priceGlass: "115.00", priceBottle: null },
    { name: "Aperol", category: "Aperitif", priceGlass: "110.00", priceBottle: null },
    { name: "Martini Dry", category: "Aperitif", priceGlass: "105.00", priceBottle: null },
    { name: "Martini Rosso", category: "Aperitif", priceGlass: "105.00", priceBottle: null },
    { name: "Disaronno Amareto", category: "Liqueur", priceGlass: "135.00", priceBottle: null },
    { name: "Baileys", category: "Liqueur", priceGlass: "115.00", priceBottle: null },
    { name: "Jagermeister", category: "Liqueur", priceGlass: "115.00", priceBottle: null },
    { name: "Fernet Menta", category: "Liqueur", priceGlass: "115.00", priceBottle: null },
    { name: "Kahlua", category: "Liqueur", priceGlass: "115.00", priceBottle: null },
    { name: "Flamingo Cherry", category: "Liqueur", priceGlass: "95.00", priceBottle: null },
    { name: "Flamingo Peach", category: "Liqueur", priceGlass: "95.00", priceBottle: null },
    { name: "Flamingo Curacao", category: "Liqueur", priceGlass: "95.00", priceBottle: null },
    { name: "Porto Ferreira Tawny", category: "Liqueur", priceGlass: "140.00", priceBottle: null },
    { name: "Chartruse de Hierbas verde", category: "Liqueur", priceGlass: "185.00", priceBottle: null },
    { name: "Midori de Melon", category: "Liqueur", priceGlass: "135.00", priceBottle: null },
    { name: "Licor de naranja Controy", category: "Liqueur", priceGlass: "110.00", priceBottle: null },
    { name: "Cinzano to spritz dry", category: "Liqueur", priceGlass: "110.00", priceBottle: null },
    { name: "Campari Vermouth", category: "Liqueur", priceGlass: "110.00", priceBottle: null },
    { name: "Licor de 43", category: "Liqueur", priceGlass: "135.00", priceBottle: null },
    { name: "Branca Menta de hiervas", category: "Liqueur", priceGlass: "120.00", priceBottle: null },
    { name: "Angostura bitters", category: "Liqueur", priceGlass: "140.00", priceBottle: null },
    { name: "St-Germain", category: "Liqueur", priceGlass: "160.00", priceBottle: null },
    { name: "Frangelico Hazelnut", category: "Liqueur", priceGlass: "135.00", priceBottle: null }
];
